all:
	  @ndk-build -B\
	   NDK_PROJECT_PATH=.\
           NDK_APPLICATION_MK=./Application.mk\
	   APP_BUILD_SCRIPT=./Android.mk

clean:
	  @ndk-build clean\
	   NDK_PROJECT_PATH=.\
           NDK_APPLICATION_MK=./Application.mk\
	   APP_BUILD_SCRIPT=./Android.mk
