all:
	  @$(NDK_HOME)/ndk-build -B\
	   NDK_PROJECT_PATH=.\
           NDK_APPLICATION_MK=./Application.mk\

clean:
	  @$(NDK_HOME)/ndk-build clean\
	   NDK_PROJECT_PATH=.\
           NDK_APPLICATION_MK=./Application.mk\
