NDK_HOME = C:\Users\test\AppData\Local\Android\Sdk\ndk\25.1.8937393
all:
	  @$(NDK_HOME)/ndk-build -B\
	   NDK_PROJECT_PATH=.\
           NDK_APPLICATION_MK=./Application.mk\

clean:
	  @$(NDK_HOME)/ndk-build clean\
	   NDK_PROJECT_PATH=.\
           NDK_APPLICATION_MK=./Application.mk\